baseURL: https://realeinherjar.github.io/
languageCode: en-us
theme: WonderMod
title: "Einherjar"
copyright: "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableGitInfo: true

permalinks:
  posts: "/:filename"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "Einherjar"
  description: "Bitcoin Maximalist and Software Engineer"
  keywords: [Bitcoin, cryptography, blog, security, privacy, Rust, Linux]
  author: "Einherjar"
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: false
    favicon: "/assets/favicon.ico"

  profileMode:
    enabled: true
    Title: "Bitcoin Maximalist Software Engineer"
    # Subtitle: "I like to write about Bitcoin, cryptography, security, privacy, Rust, and Linux."
    imageUrl: "/assets/pp.jpeg"
    imageTitle: "Profile Pic"

  socialIcons:
    - name: github
      url: "https://github.com/realeinherjar"
    - name: twitter
      url: https://primal.net/p/npub1mcgkta7n5ptnha34acasmld7z3psp6lwlmqgqwzp9c4jevnv25lqm02agr
    - name: email
      url: "mailto:realeinherjar@proton.me"
    - name: rss
      url: /index.xml
    - name: pgpkey
      url: "/assets/publickey.txt"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/realeinherjar/realeinherjar.github.io/blob/main/content"
    Text: "Source code" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "summary"]

#Enabling Search
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  highlight:
    style: dracula
    noClasses: false
    guessSyntax: true

menu:
  main:
    - identifier: about
      name: About
      url: about
      weight: 5
    - identifier: blog
      name: Blog
      url: posts/
      weight: 10
    - identifier: search
      name: Search
      url: search/
      weight: 10
